# Generated by Django 4.2.7 on 2025-12-09 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_add_group_id_to_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit'), ('login', 'Login'), ('logout', 'Logout'), ('application_start', 'Application Start'), ('application_complete', 'Application Complete'), ('document_upload', 'Document Upload'), ('ai_interaction', 'AI Interaction'), ('error', 'Error')], max_length=50)),
                ('event_category', models.CharField(choices=[('user', 'User'), ('application', 'Application'), ('document', 'Document'), ('ai', 'AI'), ('system', 'System')], max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['user'], name='analytics_e_user_id_cd8466_idx'), models.Index(fields=['event_type'], name='analytics_e_event_t_acfd0a_idx'), models.Index(fields=['event_category'], name='analytics_e_event_c_de552e_idx'), models.Index(fields=['created_at'], name='analytics_e_created_7b5fb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'), models.Index(fields=['resource_type'], name='audit_log_resourc_3f15e1_idx'), models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx')],
            },
        ),
    ]
