# Generated by Django 4.2.7 on 2025-11-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('is_voice_chat', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('error', 'Error')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversation',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('information_gathering', 'Information Gathering'), ('document_collection', 'Document Collection'), ('loan_matching', 'Loan Matching'), ('closing', 'Closing'), ('system', 'System')], max_length=50)),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_prompt',
                'indexes': [models.Index(fields=['name'], name='ai_prompt_name_c9491d_idx'), models.Index(fields=['category'], name='ai_prompt_categor_6986d6_idx'), models.Index(fields=['is_active'], name='ai_prompt_is_acti_8b1507_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('document', 'Document'), ('system', 'System')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio_duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_integration.conversation')),
            ],
            options={
                'db_table': 'ai_message',
                'indexes': [models.Index(fields=['conversation'], name='ai_message_convers_b73633_idx'), models.Index(fields=['sender'], name='ai_message_sender_5492b6_idx'), models.Index(fields=['created_at'], name='ai_message_created_dd4af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Knowledge entries',
                'db_table': 'ai_knowledge',
                'indexes': [models.Index(fields=['category'], name='ai_knowledg_categor_0d451e_idx'), models.Index(fields=['title'], name='ai_knowledg_title_a4b369_idx'), models.Index(fields=['is_active'], name='ai_knowledg_is_acti_f74ebf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user'], name='ai_conversa_user_id_7405ad_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_id'], name='ai_conversa_session_6836e8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='ai_conversa_status_be57f8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['started_at'], name='ai_conversa_started_b2008c_idx'),
        ),
    ]
