# Generated by Django 4.2.7 on 2025-12-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Updated'), ('loan_application', 'Loan Application Submitted'), ('loan_view', 'Loan Application Viewed'), ('loan_status_change', 'Loan Status Changed'), ('document_upload', 'Document Uploaded'), ('document_view', 'Document Viewed'), ('chat_message', 'Chat Message Sent'), ('voice_chat', 'Voice Chat Session'), ('payment', 'Payment Made'), ('commission_earned', 'Commission Earned'), ('user_created', 'User Account Created'), ('password_change', 'Password Changed'), ('settings_change', 'Settings Changed'), ('export_data', 'Data Exported'), ('other', 'Other Activity')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_e0c66f_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_cdda35_idx'), models.Index(fields=['-created_at'], name='user_activi_created_309e54_idx')],
            },
        ),
    ]
