# Generated by Django 4.2.7 on 2025-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('tpb', 'Third-Party Broker'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin'), ('system_admin', 'System Admin')], default='applicant', max_length=20),
        ),
    ]
