# Generated by Django 4.2.7 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('tpb_manager', 'TPB Manager'), ('tpb_staff', 'TPB Staff'), ('tpb_customer', 'TPB Customer')], default='tpb_customer', max_length=20),
        ),
    ]
