# Generated by Django 4.2.7 on 2025-12-08 08:40

from django.db import migrations


def migrate_roles(apps, schema_editor):
    """Migrate old roles to new role system"""
    User = apps.get_model('authentication', 'User')
    
    # Mapping from old roles to new roles
    role_mapping = {
        'admin': 'tpb_manager',           # admin becomes tpb_manager
        'superadmin': 'system_admin',     # superadmin becomes system_admin
        'system_admin': 'system_admin',   # system_admin stays the same
        'tpb': 'tpb_staff',               # tpb becomes tpb_staff
        'applicant': 'tpb_customer',      # applicant becomes tpb_customer
    }
    
    # Update all users
    for user in User.objects.all():
        new_role = role_mapping.get(user.role)
        if new_role and user.role != new_role:
            user.role = new_role
            user.save()
            print(f"Updated user {user.email}: {user.role} → {new_role}")


def reverse_migrate_roles(apps, schema_editor):
    """Reverse the role migration (for rollback)"""
    User = apps.get_model('authentication', 'User')
    
    # Reverse mapping
    reverse_mapping = {
        'tpb_manager': 'admin',
        'system_admin': 'superadmin',
        'tpb_staff': 'tpb',
        'tpb_customer': 'applicant',
    }
    
    # Revert all users
    for user in User.objects.all():
        old_role = reverse_mapping.get(user.role)
        if old_role and user.role != old_role:
            user.role = old_role
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_update_user_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
