# Generated by Django 4.2.7 on 2025-12-08 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_update_user_roles_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(help_text='Unique group identifier for this organization', unique=True)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'tpb_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['group_id'], name='organizatio_group_i_bec560_idx'), models.Index(fields=['owner'], name='organizatio_owner_i_0051c7_idx')],
            },
        ),
    ]
