# Generated by Django 4.2.7 on 2025-12-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_organization_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique invitation code', max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email address this code is for (optional)', max_length=254, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this code expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='authentication.organization')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_via_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation Code',
                'verbose_name_plural': 'Invitation Codes',
                'db_table': 'invitation_codes',
                'indexes': [models.Index(fields=['code'], name='invitation__code_b5d026_idx'), models.Index(fields=['organization'], name='invitation__organiz_f738b0_idx'), models.Index(fields=['is_used'], name='invitation__is_used_8d9dae_idx')],
            },
        ),
    ]
