# Generated by Django 4.2.7 on 2025-11-23 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('loan_purpose', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_term', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('funded', 'Funded'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('funding_date', models.DateTimeField(blank=True, null=True)),
                ('lender_response', models.TextField(blank=True, null=True)),
                ('ai_conversation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans_application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loans_applicationstatushistory',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('api_key_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('minimum_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supported_loan_types', models.JSONField(blank=True, default=dict)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans_lender',
            },
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term', models.IntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees', models.JSONField(blank=True, default=dict)),
                ('terms', models.TextField()),
                ('expiration_date', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loans.application')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.lender')),
            ],
            options={
                'db_table': 'loans_loanoffer',
            },
        ),
        migrations.AddIndex(
            model_name='lender',
            index=models.Index(fields=['name'], name='loans_lende_name_3d57ee_idx'),
        ),
        migrations.AddIndex(
            model_name='lender',
            index=models.Index(fields=['is_active'], name='loans_lende_is_acti_438a0d_idx'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='loans.application'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.applicantprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.lender'),
        ),
        migrations.AddField(
            model_name='application',
            name='tpb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.tpbprofile'),
        ),
        migrations.AddIndex(
            model_name='loanoffer',
            index=models.Index(fields=['application'], name='loans_loano_applica_e0592d_idx'),
        ),
        migrations.AddIndex(
            model_name='loanoffer',
            index=models.Index(fields=['lender'], name='loans_loano_lender__2880fc_idx'),
        ),
        migrations.AddIndex(
            model_name='loanoffer',
            index=models.Index(fields=['created_at'], name='loans_loano_created_69f029_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application'], name='loans_appli_applica_999b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['created_at'], name='loans_appli_created_5f18f9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='loans_appli_applica_70d28c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='loans_appli_status_fc4788_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='loans_appli_created_8daa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='loans_appli_applica_1414b2_idx'),
        ),
    ]
