# Generated by Django 4.2.7 on 2025-12-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(choices=[(0, 'Application Submitted'), (1, 'Initial Review'), (2, 'Document Verification'), (3, 'Credit Check'), (4, 'Final Approval'), (5, 'Funding')], default=0)),
                ('step_0_completed', models.BooleanField(default=True)),
                ('step_0_completed_at', models.DateTimeField(auto_now_add=True)),
                ('step_0_notes', models.TextField(blank=True, null=True)),
                ('step_1_completed', models.BooleanField(default=False)),
                ('step_1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_1_notes', models.TextField(blank=True, null=True)),
                ('step_2_completed', models.BooleanField(default=False)),
                ('step_2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_2_notes', models.TextField(blank=True, null=True)),
                ('step_2_documents_verified', models.JSONField(blank=True, default=dict)),
                ('step_3_completed', models.BooleanField(default=False)),
                ('step_3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_3_notes', models.TextField(blank=True, null=True)),
                ('step_3_credit_check_result', models.JSONField(blank=True, default=dict)),
                ('step_4_completed', models.BooleanField(default=False)),
                ('step_4_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_4_notes', models.TextField(blank=True, null=True)),
                ('step_4_decision', models.CharField(blank=True, max_length=20, null=True)),
                ('step_5_completed', models.BooleanField(default=False)),
                ('step_5_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_5_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='loans.application')),
                ('step_1_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_1_completions', to=settings.AUTH_USER_MODEL)),
                ('step_2_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_2_completions', to=settings.AUTH_USER_MODEL)),
                ('step_3_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_3_completions', to=settings.AUTH_USER_MODEL)),
                ('step_4_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_4_completions', to=settings.AUTH_USER_MODEL)),
                ('step_5_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_5_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans_applicationprogress',
                'indexes': [models.Index(fields=['application'], name='loans_appli_applica_240699_idx'), models.Index(fields=['current_step'], name='loans_appli_current_b152ea_idx')],
            },
        ),
    ]
