# Generated by Django 4.2.7 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_applicationprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization/workspace group_id for TPB workspace isolation', null=True),
        ),
    ]
