# Generated by Django 4.2.7 on 2025-12-06 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='group_id',
            field=models.UUIDField(blank=True, help_text='Group ID that this subscription covers', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='llm_tokens_limit',
            field=models.IntegerField(default=100000, help_text='Monthly LLM token limit'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=10, help_text='Maximum users in group'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='voice_tokens_limit',
            field=models.IntegerField(default=50000, help_text='Monthly voice token limit'),
        ),
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('voice_tokens_used', models.IntegerField(default=0)),
                ('llm_tokens_limit', models.IntegerField()),
                ('voice_tokens_limit', models.IntegerField()),
                ('llm_warning_sent', models.BooleanField(default=False)),
                ('voice_warning_sent', models.BooleanField(default=False)),
                ('llm_limit_reached', models.BooleanField(default=False)),
                ('voice_limit_reached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_summaries', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'usage_summary',
                'indexes': [models.Index(fields=['subscription', 'period_start'], name='usage_summa_subscri_43f72d_idx'), models.Index(fields=['group_id'], name='usage_summa_group_i_e36997_idx')],
                'unique_together': {('subscription', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(help_text='Group ID for this usage')),
                ('usage_type', models.CharField(choices=[('llm', 'LLM Tokens'), ('voice', 'Voice Tokens')], max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('user_id', models.UUIDField(blank=True, help_text='User who consumed the tokens', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (conversation_id, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'token_usage',
                'indexes': [models.Index(fields=['subscription', 'usage_type'], name='token_usage_subscri_d2d502_idx'), models.Index(fields=['group_id', 'created_at'], name='token_usage_group_i_9359f1_idx'), models.Index(fields=['created_at'], name='token_usage_created_f867dc_idx')],
            },
        ),
    ]
